[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@neondatabase/serverless"]

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "dist"
  framework = "#custom"

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"

